### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by humphd** [lyu4321/jellybean#10]
In https://github.com/lyu4321/jellybean/blob/main/index.js#L101-L103, and elsewhere, you log error messages. However, you can improve this a few ways.

1. The first fix is to make sure that you exit when there is an error.  Logging is not enough, since your program will then continue on to the next part after the `if` block.  If you're in an error state, this can cause undefined behaviour.
2. When you display an error message, do it to `stderr` vs. `stdout`, and include a useful error message to help the user correct their mistake: `console.error('An error message here...');`
3. Consider exiting the program if you can't recover from the error, and give an error code (non-zero): `process.exit(-1);`

```js
if(err) {
  console.error('...');
  process.exit(-1);
}
// rest of code here if things are ok...
```

**Comment by lyu4321** [comment]
I've updated the code to exit when encountering an error, changed console.log to console.error, and also added more descriptive error messages. Thanks for the suggestions!
