### ISSUE TITLE
Suggestion for README.md improvements

### ISSUE THREAD

**Issue by mqnguyen5** [lyu4321/jellybean#2]
* You can include an installation guide for the tool. Since I'm familiar with Node, figuring it out is not a problem. However, other developers with little to no experience in Node might require more assistance.
* Your documentation should include aliases for the available options. The current one only shows the full name, and the only way for developers to find out if there are aliases is either by taking a look at your code or installing the tool and use it.
* It would be nice to have an example or a link to a live demo so others can see how the generated output should look like.

**Comment by lyu4321** [comment]
Thanks for all the suggestions. I've updated the README to include an installation guide and demo.
