### ISSUE TITLE
Unable to process file/folder input name with spaces

### ISSUE THREAD

**Issue by mqnguyen5** [lyu4321/jellybean#3]
When I try to run the program ((notice the space between letters in the `.txt` file's name):
```
node src/index.js ./Sherlock-Holmes-Selected-Stories/Silver Blaze.txt
```
It displays an error message saying `Missing required argument: input` although the file exists.

I think the problem might be how [yargs](https://github.com/yargs/yargs) process arguments. Since they are separated with spaces, only a part of the file name will be passed into `argv.input`

For example:
```
node src/index.js ./Sherlock-Holmes-Selected-Stories/Silver Blaze.txt

console.log(argv.input) // contains only [some-path]/Sherlock-Holmes-Selected-Stories/Silver => error
```

**Comment by lyu4321** [comment]
Thanks! This has been fixed
