### ISSUE TITLE
Links for non-text files are still being displayed

### ISSUE THREAD

**Issue by mqnguyen5** [lyu4321/jellybean#4]
Given a `folder` directory with the following files:
```
2efgt.bin  'a text file.txt'   abcd.txt   jkjkjk.js
```

When run the program using `node src/index.js -i ~/[some-path-name]/folder/`, the generated links in one of the `html` file is as follows:
```html
<div>
    <ul> 
        <li><a href="./2efgt.html">2efgt</a></li>
        <li><a href="./a text file.html">A text file</a></li>
        <li><a href="./abcd.html">Abcd</a></li>
        <li><a href="./jkjkjk.html">Jkjkjk</a></li>
    </ul>
</div>
```

As you can see, while `jkjkjk` and `2efgt` are not text files, the program still generates their links.

To fix it, from line 96-101, you could add an `Array.filter()` to eliminate any non-text files before calling `readFile()`.

**Comment by lyu4321** [comment]
This has been fixed as well. Thank you!

**Comment by mqnguyen5** [comment]
I have tested the code. Everything is working as expected.
