### ISSUE TITLE
Suggestion for code documentation

### ISSUE THREAD

**Issue by mqnguyen5** [lyu4321/jellybean#5]
I would suggest adding some comments for each of the function. This will help improve maintainability as you will be able to take a look at the code in the future and still able to understand what each function do. In addition, the detailed documentation will make it easier for other developers to contribute to your project.

Example:
```
/**
 * What it does...
 * @param [name] {*} => desc of the param...
 * @return
 * etc.
 */
 function someFunctionName() {...}
```

**Comment by lyu4321** [comment]
This has been updated :) Thank you
