### ISSUE TITLE
README fixes

### ISSUE THREAD

**Issue by humphd** [lyu4321/jellybean#7]
In your readme, a few things I'd like to see addressed:

1. Expand the section https://github.com/lyu4321/jellybean#running-the-program in order to explain what each of these is doing, why you'd do it, etc.  Try to teach the user how to use your program.
2. Add syntax highlighting to the HTML example file you list using `html` after the backticks, see https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by lyu4321** [comment]
Thanks, I've added some more details as well as syntax highlighting.
