### ISSUE TITLE
Remove unnecessary dependencies

### ISSUE THREAD

**Issue by humphd** [lyu4321/jellybean#8]
You have a number of dependencies that aren't required:

1. The [fs and path modules](https://github.com/lyu4321/jellybean/blob/main/package.json#L13-L14) are both built into node, so you don't add them this way
2. You don't need to include yarn as a dependency: it's a build tool you call, not require.

**Comment by lyu4321** [comment]
Thank you, I have removed the unnecessary dependencies.
